apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gotify.fullname" . }}
  labels:
    {{- include "gotify.labels" . | nindent 4 }}
{{- with .Values.env }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}

