# Default values for certificate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

issuerGroup: cert-manager.io
issuerType: ClusterIssuer
issuerName: production

dnsNames:
  - foo.bar.com

usages:
  - digital signature
  - key encipherment
