apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging
spec:
  acme:
    email: {{ .Values.email }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: staging-key
    solvers:
      - http01:
          ingress:
            ingressClassName: {{ .Values.ingressClassName }}
