apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "awx.fullname" . }}
  labels:
    {{- include "awx.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.awx.password | b64enc | quote }}
