title: "SCS Startpage"
subtitle: Sovereign Cloud Stack
logo: "https://raw.githubusercontent.com/SovereignCloudStack/website/main/_assets/android-chrome-512x512.png"
header: true
footer: false
theme: default
colors:
  light:
    highlight-primary: "#ffffff"
    highlight-secondary: "#50c3a5"  # scs green
    highlight-hover: "#7d7d82"  # scs grey
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#000000"
    text-title: "#303030"
    text-subtitle: "#0f5fe1"  # scs blue
    card-shadow: "rgba(0, 0, 0, 0.1)"
    link-hover: "#363636"
  dark:
    highlight-primary: "#0f5fe1"  # scs blue
    highlight-secondary: "#7d7d82"
    highlight-hover: "#131313"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#7d7d82"  # scs grey
    text-header: "#000000"
    text-title: "#50c3a5"  # scs green
    text-subtitle: "#f5f5f5"
    card-shadow: "rgba(0, 0, 0, 0.4)"
    link-hover: "#ffdd57"
links:
  - name: "Homepage"
    icon: "fas fa-house"
    url: "https://scs.community/"
    target: "_blank"
  - name: "Documentation"
    icon: "fas fa-book"
    url: "https://scs.community/docs/contributor/"
    target: "_blank"
  - name: "Bug report"
    icon: "fas fa-bug"
    url: "https://github.com/SovereignCloudStack/issues"
    target: "_blank"
services:
  - name: "Community"
    icon: "fas fa-user"
    items:
      - name: "Jitsi"
        logo: "https://jitsi.org/wp-content/themes/jitsi/images/logo-web-2020.png"
        subtitle: "Video conferencing"
        tag: "community"
        url: "https://conf.scs.koeln:8443/beermann"
        target: "_blank"
      - name: "Mailman"
        logo: "https://docs.mailman3.org/en/latest/_static/logo2010-2.jpg"
        subtitle: "Mailing list management"
        tag: "community"
        url: "https://scs.sovereignit.de/mailman3/postorius/"
        target: "_blank"
      - name: "Nextcloud"
        logo: "https://avatars.githubusercontent.com/u/19211038?s=200&v=4"
        subtitle: "Document share"
        tag: "share"
        url: "https://ms.scs.sovereignit.de/nextcloud/"
        target: "_blank"
  - name: "Development"
    icon: "fas fa-wrench"
    items:
      - name: "GitHub"
        logo: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
        subtitle: "Public Code"
        tag: "development"
        url: "https://github.com/SovereignCloudStack"
        target: "_blank"
      - name: "Okeanos"
        logo: "https://github.com/gardener/gardener/raw/master/logo/gardener-large.png"
        subtitle: "Kubernetes cluster Orchestrator"
        tag: "kubernetes"
        url: "https://dashboard.okeanos.dev/"
        target: "_blank"
  - name: "Planning"
    icon: "fas fa-toolbox"
    items:
      - name: "Wekan"
        logo: "https://wekan.github.io/wekan-logo.svg"
        subtitle: "Public Code"
        tag: "planning"
        url: "https://scs.sovereignit.de/wekan"
        target: "_blank"
      - name: "Etherpad"
        logo: "https://raw.githubusercontent.com/ether/etherpad-lite/develop/src/static/img/brand.svg"
        subtitle: "Collaborative note taking"
        tag: "collaboration"
        url: "https://input.osb-alliance.de/"
        target: "_blank"
  - name: "Clouds"
    icon: "fas fa-warehouse"
    items:
      - name: "Pluscloud Open"
        logo: "https://www.plusserver.com/hubfs/cms_assets/symbols-prod/symbol-prod-pluscloud_open.svg"
        subtitle: "SCS cloud"
        tag: "cloud"
        url: "https://ui.gx-scs.sovereignit.cloud/auth/login/?next=/"
        target: "_blank"
