---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "default-helmchart.fullname" . }}
  labels:
    {{- include "default-helmchart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "default-helmchart.selectorLabels" . | nindent 4 }}
