apiVersion: v1
kind: Secret
metadata:
  name: {{ include "longhorn-s3-backup-secret.fullname" . }}
  labels:
    {{- include "longhorn-s3-backup-secret.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.access_key | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret_key | b64enc | quote }}
  AWS_REGION: {{ .Values.region | b64enc | quote }}
  AWS_ENDPOINTS: {{ .Values.endpoint | b64enc | quote }}
