{{/* inspired by https://gist.github.com/nezed/c57eb6fad209df0508821f322b19e9b0 */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "basic-auth.fullname" . }}
  labels:
    {{- include "basic-auth.labels" . | nindent 4 }}
type: Opaque
data:
  {{/* htpasswd is available since helm@3.2.0 */}}
  auth: {{ (htpasswd .Values.username .Values.password) | b64enc | quote }}
