kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "pvc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pvc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "pvc.chart" . }}
  annotations:
  {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  accessModes:
  - {{ .Values.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.size | quote }}
{{- if .Values.storageClass }}
{{- if (eq "-" .Values.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.storageClass }}"
{{- end }}
{{- end }}