apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
