---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-welcome.fullname" . }}
  labels:
    {{- include "nginx-welcome.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nginx-welcome.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-welcome.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "nginx:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
