apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homer-startpage.fullname" . }}
  labels:
    {{- include "homer-startpage.labels" . | nindent 4 }}
data:
  config: |-
    {{ .Values.homerConfig | toYaml | nindent 4 }}
